services: docker
language: python
python:
  - '3.6'

env:
  matrix:
    - ARCH=i386
    - ARCH=amd64
    - ARCH=arm
    - ARCH=aarch64

install:
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_USER" --password-stdin
  - pip install pipenv
  - pipenv sync --dev

before_script:
  - ./build.sh $ARCH
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
  - export PIPENV_IGNORE_VIRTUALENVS=1
  - pipenv check
  - pipenv run pytest -v

deploy:
  # Deploy tag
  - provider: script
    script:
      docker build --build-arg COMMIT_ID=$TRAVIS_COMMIT -t tomsquest/docker-radicale:$ARCH.$TRAVIS_TAG --file Dockerfile.$ARCH . &&
      docker push tomsquest/docker-radicale:$ARCH.$TRAVIS_TAG;
    skip_cleanup: true
    on:
      tags: true
  # Deploy latest
  - provider: script
    script:
      docker build --build-arg COMMIT_ID=$TRAVIS_COMMIT -t tomsquest/docker-radicale:$ARCH --file Dockerfile.$ARCH . &&
      docker push tomsquest/docker-radicale:$ARCH;
    skip_cleanup: true
    on:
      branch: master
